export default [
    { "_id": "A101", "title": "Propulsion Assignment", "course": "RS101", "available":  "January 20 at 12:00am", "due": "January 27 at 11:59pm", "available_until": "February 3 at 11:59pm", "points": "100", "description": "Explain the differences between liquid and solid rocket engines. Provide multiple examples of both." },
    { "_id": "A102", "title": "Combustion Analysis", "course": "RS101", "available":  "January 27 at 12:00am", "due": "February 3 at 11:59pm", "available_until": "February 10 at 11:59pm","points": "100", "description": "Perform an analysis exploring if jet fuel can burn hot enough to melt steel beams." },
    { "_id": "A103", "title": "Nozzle Design Project", "course": "RS101", "available":  "February 3 at 12:00am", "due": "February 10 at 11:59pm", "available_until": "February 17 at 11:59pm","points": "100", "description": "Using CAD, provide a 3D model for an efficient nozzle intended to deliver an air/fuel mixture a rocket engine. Hint: consider taking inspiration from commercial soft drink dispensers." },
    { "_id": "A201", "title": "Aerodynamics Quiz", "course": "RS102", "available":  "January 20 at 12:00am", "due": "January 27 at 11:59pm", "available_until": "February 3 at 11:59pm","points": "100", "description": "10 question quiz covering topics from weeks 1 - 4." },
    { "_id": "A202", "title": "Flow Analysis", "course": "RS102", "available":  "January 27 at 12:00am", "due": "February 3 at 11:59pm", "available_until": "February 10 at 11:59pm","points": "100", "description": "Analyze the lyrical flow from 2:10 to 3:00 of Kendrick Lamar's Untitled 05 | 09.21.2014." },
    { "_id": "A203", "title": "Heating Analysis", "course": "RS102", "available":  "February 3 at 12:00am", "due": "February 10 at 11:59pm", "available_until": "February 17 at 11:59pm","points": "100", "description": "Describe the properties of a material ideal for shielding spacecraft from the heat expedrienced during re-entry into Earth's atmosphere. Explain the materials that are used today for this purpose and their advantages and shortcomings." },
    { "_id": "A301", "title": "Structural Design Task", "course": "RS103", "available":  "January 20 at 12:00am", "due": "January 27 at 11:59pm", "available_until": "February 3 at 11:59pm","points": "100", "description": "Using CAD, design a pod capable of safely returning live astronauts to the surface of the earth. Hint: it is typically ideal to touch down into the ocean." },
    { "_id": "A302", "title": "Orbital Calculations", "course": "RS103", "available":  "January 27 at 12:00am", "due": "February 3 at 11:59pm", "available_until": "February 10 at 11:59pm","points": "100", "description": "Provide a detailed plan for launching a space probe meant to touch down on the surface of Mars. Provide any relevant calculations and include both a launch and touchdown date." },
    { "_id": "A303", "title": "Systems Engineering Exam", "course": "RS103", "available":  "February 3 at 12:00am", "due": "February 10 at 11:59pm", "available_until": "February 17 at 11:59pm","points": "100", "description": "25 question midterm exam covering topics from the first half of the semester." }
  ];